# NOTE: on MacOS you need to add an addition flag: -undefined dynamic_lookup
default:
	c++ -O3 -Wall -shared -std=c++11 -IE:\MiniConda\envs\d2l\Include -IE:\MiniConda\envs\d2l\lib\site-packages\pybind11\include src/simple_ml_ext.cpp -o src/simple_ml_ext.pyd -LE:\MiniConda\envs\d2l\libs -lpython39


